[project]
name = "multistatehnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bokeh>=3.7.3",
    "jax>=0.6.1",
    "matplotlib>=3.10.3",
    "plotly>=6.1.2",
]
