# Base config for hydra_test.py
# Hydra will load this when running hydra_test.py

app:
  name: multistatehnn
  seed: 42

paths:
  # Prefer PROJECT_ROOT env when set, otherwise use launch CWD
  project_root: ${oc.env:PROJECT_ROOT,${hydra:runtime.cwd}}
  data_dir: ${paths.project_root}/data
  output_dir: ${paths.project_root}/output

training:
  epochs: 10
  lr: 0.001

hydra:
  # Keep current working directory; still create run.dir for hydra artifacts
  job:
    chdir: false
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${paths.output_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
