# Base config for hydra_test.py
# Hydra will load this when running hydra_test.py

seed: 0

defaults:
  - override hydra/job_logging: disabled

hydra:
  # jobの設定
  job:
    chdir: false   # Run in job's directory
  output_subdir: null   # hydraのログを作らない

  run:    # Run settings
    dir: ./output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/seed=${seed}

  # multirun用の設定
  sweeper:    # Sweeper settings
    params:
      seed: range(3)
  sweep:  # Sweep settings
    dir: ./output/${hydra.job.name}/multirun
    subdir: seed=${seed}
